### ISSUE TITLE
A.03.IR221.TGR53.serviceMetadata (page 8)

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-download-predefined-wfs#26] opened 2016-03-23 10:14 UTC
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

In the Purpose you can choose between EITHER metadata to be linked to via an inspire_common:MetadataURL OR put all metadata element in ExtendedCapabilities.
In the test, it says to test all metadata elements in ExtendedCapabilities irrespective of inspire_common:MetadataURL is there.
# Proposed Change

To conform with the purpose of the test, change position of the two last check points, 
- If a inspire_common:MetadataURL is provided, request the Metadata document with this URL. Check if the response is a valid Metadata document.
- Else, check if all mandatory metadata elements as specified in Table 4 of the TG exist in the ExtendedCapabilities section.

Also clarify how to validate the Metadata document in the first check above; the schema to be used and/or that it should conform with Table 4.

**Comment by thijsbrentjens** [comment] 2016-04-04 09:19
Duplicate of #22 and #23 / #25. The proposal here is maybe a better one to use than the one in #22.

**Comment by cportele** [comment] 2016-04-05 12:21
Yes, see the discussion in the linked issues.

**Comment by cportele** [comment] 2016-05-21 13:44
Proposed change accepted.

**Closed as completed** 2016-08-01 16:07 UTC
Labels: type:CT, sev:medium, comm:SE, status:implemented, res:accepted-with-modifications
