### ISSUE TITLE
A.03.IR221.TGR53.serviceMetadata

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-download-predefined-wfs#25] opened 2016-03-23 10:14 UTC
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

From the test method it is not clear how to validate the metadata document for being valid. Needs more clarification.
# Proposed Change

Specify how metadata validation must be done. For example: validate the metadata document to the XML schema.

**Comment by thijsbrentjens** [comment] 2016-04-04 09:17
Duplicate of #23?

**Comment by cportele** [comment] 2016-04-05 14:53
Yes, see #23

**Closed as completed** 2016-08-01 16:07 UTC
Labels: type:ED, sev:minor, comm:NL, status:implemented, res:accepted
